### ISSUE TITLE
Failure compiling MRI

### ISSUE THREAD

**Issue by alexeagle** [bazel-contrib/rules_ruby#44]
Have you seen something like this?

This error feels to me like the repository rule is trying to write to some global location on my disk, and maybe we need to set an environment variable like `XRUBY_RUBYLIBDIR` somewhere so the MRI build process is okay with running in some read-only sandbox?

I'm on Linux, tried ruby 3.0.6 and 3.2.2, get an error like the following

```
x86_64-linux-fake.rb updated
external command failed with status 2

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 19.5M  100 19.5M    0     0  7329k      0  0:00:02  0:00:02 --:--:-- 7329k
./tool/mkconfig.rb:272:in `write': Permission denied @ io_write - <STDOUT> (Errno::EACCES)
        from ./tool/mkconfig.rb:272:in `print'
        from ./tool/mkconfig.rb:272:in `<main>'
make: *** [uncommon.mk:879: .rbconfig.time] Error 1
make: *** Waiting for unfinished jobs....

BUILD FAILED (Ubuntu 20.04 on x86_64 using ruby-build 20231114)
```

I do have a system ruby already 

```
$ ruby -v
ruby 3.2.2 (2023-03-30 revision e51014f9c0) [x86_64-linux]
```

**Comment by p0deje** [comment]
What Linux distro is that?

**Comment by alexeagle** [comment]
Ubuntu 20.04.6 LTS

```
uname -a
Linux system76-pc 5.18.10-76051810-generic #202207071639~1659403207~20.04~cb5f582~dev-Ubuntu SMP PREEMPT_DY x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by p0deje** [comment]
I tried installing using bare Ubuntu 20.04 Docker image and it worked fine:

```bash
$ docker run --platform=linux/amd64 -v (pwd):/rules_ruby -ti ubuntu:20.04 bash
```

```bash
$ uname -a
Linux 6d3c0a69477d 6.4.16-linuxkit #1 SMP PREEMPT Wed Oct 25 16:32:24 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

# Bazelisk
$ apt-get update -y && apt-get install -y wget && wget https://github.com/bazelbuild/bazelisk/releases/download/v1.19.0/bazelisk-linux-amd64 -O /usr/local/bin/bazel && chmod +x /usr/local/bin/bazel

# Ruby deps
$ apt-get install -y build-essential libz-dev libyaml-dev perl

$ cd /rules_ruby/examples/gem
$ echo "3.0.6" > .ruby-version
$ RUBY_RULES_DEBUG=1 bazel build ...
...
INFO: Build completed successfully, 31 total actions
```

Shall I use some other Docker image to try and reproduce?

**Comment by alexeagle** [comment]
I imagine you'd want an image that already has ruby installed on the system.

**Comment by p0deje** [comment]
I've installed Ruby 2.7 using apt-get and still could get the toolchain to install w/o problems.

**Comment by alexeagle** [comment]
I have no idea, maybe with the system or from some transitive effect of `apt-get install` - lots of tooling wants a ruby interpreter.

If we can't reproduce then let's wait to see if users report it?
